#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : google-apitools
Version  : 0.5.24
Release  : 29
URL      : https://files.pythonhosted.org/packages/a9/74/14b0618bfd2c02fbddadbfa1d74e0e141e25fbea9e9197e41eddadbb1299/google-apitools-0.5.24.tar.gz
Source0  : https://files.pythonhosted.org/packages/a9/74/14b0618bfd2c02fbddadbfa1d74e0e141e25fbea9e9197e41eddadbb1299/google-apitools-0.5.24.tar.gz
Summary  : client libraries for humans
Group    : Development/Tools
License  : Apache-2.0
Requires: google-apitools-bin
Requires: google-apitools-python3
Requires: google-apitools-python
Requires: fasteners
Requires: httplib2
Requires: oauth2client
Requires: python-gflags
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : fasteners

%description
===============
        
        |pypi| |build| |coverage|
        
        ``google-apitools`` is a collection of utilities to make it easier to build
        client-side tools, especially those that talk to Google APIs.

%package bin
Summary: bin components for the google-apitools package.
Group: Binaries

%description bin
bin components for the google-apitools package.


%package python
Summary: python components for the google-apitools package.
Group: Default
Requires: google-apitools-python3

%description python
python components for the google-apitools package.


%package python3
Summary: python3 components for the google-apitools package.
Group: Default
Requires: python3-core

%description python3
python3 components for the google-apitools package.


%prep
%setup -q -n google-apitools-0.5.24

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536470195
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gen_client

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
